### ISSUE TITLE
Resource still active?

### ISSUE THREAD

**Issue by aegershman** [EngineerBetter/stopover#3]
I just found this resource. I'm intrigued, but also notice the last commit was in late 2007.

I'm curious if this resource is still in use, or if you've found a different pattern for pinning resources to a specific version.

**Comment by DanielJonesEB** [comment]
Hi @aegershman,

Yep, we still use the resource, both with our customers and on internal projects. It's fairly simple, so there's not a lot of maintenance work to do.

Were there particular features you were looking for? We've got some folks who got halfway through a blog post on Stopover before having to go onto billable work.

**Comment by aegershman** [comment]
Awesome, thank you. We're definitely interested in this, but if you could include some more practical examples, example pipelines, discussion of use-cases, _why_ this exists, how EngineerBetter uses it internally, etc., it would help clear up some of our confusion on how to best utilize it.

I totally get it if adding examples/doc isn't highest of priorities. No worries either way.

**Comment by aegershman** [comment]
Will close this. Will definitely keep an eye on this project. Thanks for making it available oss  👍
