### ISSUE TITLE
How to get latest build_id from upstream pipeline

### ISSUE THREAD

**Issue by luis-n4489** [EngineerBetter/stopover#8]
If I have a pipeline that requires to fetch the build_id in order to know which resource build id to run stopover against - what would be the best route?

**Comment by DanielJonesEB** [comment]
Hey, I'm guessing you figured this out? Please let us know if you'd still like help.

**Comment by luis-n4489** [comment]
still not sure how i would so it to a pipeline up or downstream to then trigger itself to run or etc
